travis:
  secure:
    BINSTAR_TOKEN: LGz0PdkhKZqkIvbFezaqcSouDNR5InIYNpa9AetgtGpYpJquwXdZIh5HPrcs4rObsdKBDD1H4Xa0Lnci2FwGRRM9Cf7Tu3mJo3jTG96POgbvkC0prK7IfZlzk6ZZMSYckEP0Q/uv8BIwpyXSH2VFHdSnegi+fB+beVSg+su8TtExmeg9yAaEORzWCPB0U6O70q6g+w5w777SYQgwZXUI3iWe5Pgra/2gb633seIWilbXdVfJVzjrt6vPBV63G+QlnVL+Y8yvNNEOq3al415q+D79jGK6Ztuhq8H3+XoNfxijiQz8mGAquMI7tBGTvdVLFIleSEwDqvywMGOW8lm6/upcpdHBNErz6o0Yf/T9+t2708whmO3vAYOSbBm4AcqXiwcw8wBXL9tfb3wgG2f1WjghjB0sPl4YnDWShwdzFFTMHPo4QF+Ub0zI+oNwMWLJvbr8/Oed6KYQTH77yCDLRkWwyDgupTp86q8lOHp789kKMXrZcxRiR2Yj/Ic7hVVPkIUI2eeWPuwk+GO59DR+cls0ibwF5ycEx+B2499f3s2YcPSJ5DcMbkSP/AFbiCBGdb5boRSxHVd7WxTr4badQ5zOkhKw72hyUpwGWALxJyjuKaq8d/ybLF/GbhxXTYkD3Jkwdx2EPggIUpoGNPDFzgCO6AhyqbQUvoqWbRSLa5s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
