travis:
  secure:
    BINSTAR_TOKEN: XQCusas7XcZ8LmCCSFnsV52qNjBMMmwLnOXRIP2M2VEiBNywNeccsEI0uj1UyevFlS93hNvVRxCn2JSNyy9yjy572Q7zC9vXFeuZFFCMsLJ+vkIc1nfq/5K0KX8ih0HQSrHJ3Tv37HRAl8VJUpmsOAGpLSSYqxQeu+91R7LPdmVjaWDhSbujlahb8a0fHfTM53ubjcdvx1slBBo4RrlyVb+lb7byPD+nh3jTa/Atjuuysuiq/znYZDCJ7bphOj+UJW+3KF3FmuyUM3v7C/uo8vWwWqokVSIQXXxmhXZM1DRbZHRlTumM2dw2ZuL1+OkNAJl78uuKEn1C96zjJ8747JBea8n+vULLgyaE1n8QUeOJtSnV4jBS9Wb+bP5vJM3N7Xtb0rRvUTXBuyHy/0IqcZvr4q9b7Ty1KAqiDIgfbkSsOStS+St7G2X0BdruMaUhNLrkb9cHOrdWwXELgAfinGGY9PdTApWZ4YqpcvVgeHK12WZYitQd17ADyGg7dS8+sBJ8XbmcjSGoqO75ofRcKYwGfOXHukWLs9afdR51GV24GVwDTOt4w2/2QKQFiSQAXZxg6I+JxeDKbgAKRgnXyNeel8AFfteriYrNiClhZdHbuO3sc0RLHyvWueRjvUMQzNiCdLvi0VFpa41U9l40a7ETTTpTq2gbGa9DvQ9AJLE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
